# Generated by Django 3.1.7 on 2021-04-09 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default="Hello! I'm new to Portfolio Hut.", max_length=240)),
                ('friend_requests', models.ManyToManyField(blank=True, related_name='friend_requests_list', to='portfoliohut.Profile')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends_list', to='portfoliohut.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=4)),
                ('ticker', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('quantity', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfoliohut.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('withdraw', 'WITHDRAW'), ('deposit', 'DEPOSIT')], max_length=8)),
                ('date_time', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfoliohut.profile')),
            ],
        ),
    ]
