# Generated by Django 3.1.7 on 2021-04-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfoliohut", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalequity",
            options={"ordering": ("date",)},
        ),
        migrations.RemoveField(
            model_name="portfolioitem",
            name="cost_average",
        ),
        migrations.AlterField(
            model_name="historicalequity",
            name="ticker",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="ticker",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="ticker",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="historicalequity",
            unique_together={("ticker", "date")},
        ),
    ]
