# Generated by Django 3.1.7 on 2021-04-12 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portfoliohut", "0002_add_demo_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_type",
            field=models.CharField(
                choices=[("public", "PUBLIC"), ("private", "PRIVATE")],
                default="public",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
