# Generated by Django 3.2 on 2021-04-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfoliohut", "0004_add_more_demo_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="date_time",
            field=models.DateField(),
        ),
    ]
