# Generated by Django 3.2 on 2021-04-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfoliohut", "0005_alter_stock_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="date_time",
            field=models.DateTimeField(),
        ),
    ]
